### PR TITLE
Format using refmt

### PR DESCRIPTION
**Pull request by thangngoc89**
I'm not sure what is your current IDE setup like but I'm using reason-cli@3.0.4 which includes refmt but everytime I touch a file, it formats everything

### CODE REVIEW

**Comment by threepointone** [comment]
I’m using nuclide

**Comment by thangngoc89** [comment]
I'm using VS Code but it should be irrelevant. Could you check your refmt version? 

```
refmt --version
```

Mine: 

```
refmt --version
Reason 3.0.4 @ 731e605
```

**Comment by threepointone** [comment]
Not at laptop right now, will check when back

**Comment by threepointone** [comment]
updated refmt to 3.0.4, will commit changes in next push. closing this for now. thanks for the catch!

**Pull request closed without merging**
